name: Synchronize images

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *'
  workflow_dispatch: {}
  push:
   branches:
    - main

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Install skopeo
        run: sudo apt-get install -y skopeo

      - uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: Install manifest-tools
        run: go install github.com/estesp/manifest-tool/v2/cmd/manifest-tool@latest

      - name: Install glab
        run: go install gitlab.com/gitlab-org/cli/cmd/glab@latest

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: sync
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./sync.sh
